### ISSUE TITLE
Binary distribution pitfalls

### ISSUE THREAD

**Issue by 01mf02** [gapt/gapt#496]
I downloaded the binary distribution of GAPT 2.0 via the instructions given on the main GitHub page.
However, even very simple commands from the user manual fail:

~~~
gapt> val H = hof"!x (P(x,f(x)) -> ?y P(x,y))"
<console>:109: error: value hof is not a member of StringContext
      val H = hof"!x (P(x,f(x)) -> ?y P(x,y))"
~~~

What's wrong here?

**Comment by quicquid** [comment]
Hello, the hof string interpolation was only recently added and is not yet in the stable distribution, but the manual was already changed accordingly. If you use the nightly build at https://logic.at/gapt/downloads/gapt-latest-build.tar.gz it works fine on my computer.

**Comment by gebner** [comment]
The instructions in the README are for the current version in git master, there are [nightly builds available here](https://logic.at/gapt/downloads/gapt-latest-build.tar.gz).

For instructions regarding the gapt 2.0 release, please refer to the PDF included in the tarball.  For reference, this is the [version of the example that works in gapt 2.0](https://github.com/gapt/gapt/blob/4b950211b8b7198ec4e402af198a191dc56e191b/README.md):
```scala
val firstOrderSequent = existsclosure("p(c) | p(d)" +: Sequent() :+ "p(x)" map parseFormula)
Prover9 getExpansionProof firstOrderSequent map { _.deep }
```

**Comment by 01mf02** [comment]
Thanks a lot! I now use the nightly build.
